import {
  START_MONEY,
  TARGET,
  BANKRUPTCY,
  START_ENERGY,
  ENERGY_COST_PER_QUESTION,
  ENERGY_REWARD_CORRECT,
  ENERGY_PURCHASE_AMOUNT,
  ENERGY_PURCHASE_COST,
} from '../logic/scoring';

export const CONFIG = {
  START_MONEY,
  TARGET,
  BANKRUPTCY,
  START_ENERGY,
  ENERGY_COST_PER_QUESTION,
  ENERGY_REWARD_CORRECT,
  ENERGY_PURCHASE_AMOUNT,
  ENERGY_PURCHASE_COST,
};
